### ISSUE TITLE
Add support for ReSharper 2019.2.x

### ISSUE THREAD

**Issue by SchreinerK** [hmemcpy/ReSharper.InternalsVisibleTo#14]
Please support  ReSharper 2019.2.x

**Comment by Mike-EEE** [comment]
One of two plugins that I use that have not made the jump yet... 😭

**Comment by SchreinerK** [comment]
forked and pullrequest created.
Tempororay pre build at: https://github.com/KsWare/KsWare.ReSharper.InternalsVisibleTo/releases/tag/2019.2.2-KsWare

**Comment by Mike-EEE** [comment]
@SchreinerK it's almost worth looking into submitting a `ReSharper.InternalsVisibleTo.Unofficial` package to JB as it seems this one isn't quite as updated/supported/maintained as it should be. 😞

**Comment by SchreinerK** [comment]
merged :-) 
https://github.com/hmemcpy/ReSharper.InternalsVisibleTo/pull/15

**Comment by Mike-EEE** [comment]
Woohoo!  Thank you all!  Until next time. 😁
