### ISSUE TITLE
ReSharper 9.1

### ISSUE THREAD

**Issue by RichardD2** [hmemcpy/ReSharper.InternalsVisibleTo#8]
This extension doesn't seem to be available in R# 9.1, which was released today.

**Comment by NameOfTheDragon** [comment]
Me Too.
I actually forked the project to see if just changing the dependency on "Wave 1" would work... but I couldn't get it to build. Is it more complicated than that?

**Comment by yuyuki** [comment]
Hi,

will you develop this plugin for R# 9.1 ?

Thank you

**Comment by hmemcpy** [comment]
Sorry for the lack of response.
The extension is now supported for R# 9.2 and 10.0, available in the gallery
